# Generated by Django 2.1.5 on 2019-03-20 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exerlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrydate', models.DateField()),
                ('entrytime', models.CharField(max_length=255)),
                ('caloriesburned', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'exerlog',
            },
        ),
        migrations.CreateModel(
            name='ExerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exername', models.CharField(max_length=255)),
                ('exerurl', models.URLField(blank=True, null=True)),
                ('exerscript', models.TextField()),
            ],
            options={
                'db_table': 'exertype',
            },
        ),
        migrations.AddField(
            model_name='exerlog',
            name='exertype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fitapp.ExerType'),
        ),
        migrations.AddField(
            model_name='exerlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
